name: test-check

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24.x'

      - name: Install dependencies
        run: make install

      - name: Run tests
        run: make test

      - name: Setup git config
        run: |
          git config user.name "Bot"
          git config user.email "<>"

      - name: Prepare template
        run: |
          git checkout --orphan temp-main
          echo '' > src/index.js
          git add -A
          git commit --no-verify -m "Rebuild template (auto)"
          git push -f --no-verify origin temp-main:main
